<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Launcher.props" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nunit"/>
    <PackageReference Include="Tomlyn"/>
    <PackageReference Include="NUnit.Analyzers"/>
    <PackageReference Include="NUnit3TestAdapter"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SS14.Launcher\SS14.Launcher.csproj"/>
    <Compile Include="..\Mados.Worker\ServerNotesStore.cs" Link="ServerNotesStore.cs" />
    <Compile Include="..\Mados.Worker\LauncherInsightsStore.cs" Link="LauncherInsightsStore.cs" />
    <Compile Include="..\Mados.Worker\LocalServerStore.cs" Link="LocalServerStore.cs" />
    <Compile Include="..\Mados.Worker\LocalServerManager.cs" Link="LocalServerManager.cs" />
    <Compile Include="..\Mados.Worker\LocalServerConfig.cs" Link="LocalServerConfig.cs" />
  </ItemGroup>

</Project>
